### ISSUE TITLE
请问在路由器上要做哪些操作？

### ISSUE THREAD

**Issue by KittenYang** [migege/dnspod#1]
我看到有说要做端口映射，有说要做DMZ主机，有说要给树莓派设置一个静态地址，请问正确的操作是如何？

**Comment by migege** [comment]
首先要做的是DNS解析，也就是这个脚本做的事情，把域名解析到树莓派所在网络的对外IP上；然后根据你的需求，在路由器上做相应的、必要的端口映射，比如需要ssh，那就在路由器上映射22端口这样子。给树莓派设置一个静态地址是必要的，避免DHCP分配的IP发生变化导致端口映射失效。
