### ISSUE TITLE
How to  get domain_id and record_id?

### ISSUE THREAD

**Issue by marguerite** [migege/dnspod#2]
Hi, this maybe a stupid question...

I read its API doc too...but still didn't find where I could get such IDs...

Thanks

Marguerite

**Comment by marguerite** [comment]
never mind, I got it.

**Comment by migege** [comment]
Sorry, I noticed this issue just a minute ago. Can you read Chinese? A post in my blog described the method by using API.

https://migege.com/post/dnspod-api-domain_id-record-id
